version: "3"

services:
  app:
    container_name: orderrequestapp
    restart: always
    build:
      context: frontend
    ports:
      - "3000:3000"
    links:
      - api
#    volumes:
#      - .:/usr/src/app/
  api:
    container_name: orderrequestapi
    restart: always
    build:
      context: backend
    ports:
      - "3001:3001"
    links:
      - mongo
#    volumes:
#      - "./:/usr/src/app/"
  mongo:
    container_name: mongodatabase
    image: mongo
 #   ports:
 #     - "27018:27017"
    logging:
      driver: none